# Generated by Django 4.1.3 on 2023-01-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_img',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
    ]
