# Generated by Django 4.1.3 on 2023-02-04 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0003_alter_products_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='current_val',
            field=models.CharField(max_length=14),
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('last_bid_val', models.CharField(max_length=14)),
                ('current_val', models.CharField(max_length=14)),
                ('winner', models.CharField(max_length=50)),
                ('last_bid_time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
