# Generated by Django 4.1.3 on 2023-02-05 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_products_current_val_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='status',
        ),
    ]
