# Generated by Django 4.1.3 on 2023-02-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_remove_auction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='current_val',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='winner',
        ),
    ]
