# Generated by Django 4.1.3 on 2023-02-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_remove_auction_current_val_remove_auction_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='last_bid_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
