# Generated by Django 4.1.3 on 2023-02-05 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
